// Nameplate specifications for different asset types

export const getNameplateData = (assetType, assetId) => {
  const nameplateSpecs = {
    transformer: {
      manufacturer: 'Siemens Energy',
      model: 'GEAFOL Series',
      serialNumber: `SN-${assetId}`,
      manufactureYear: '2018',
      ratedPower: '1500 kVA',
      primaryVoltage: '33 kV',
      secondaryVoltage: '415 V',
      frequency: '50/60 Hz',
      phases: '3-Phase',
      coolingType: 'ONAN (Oil Natural Air Natural)',
      vectorGroup: 'Dyn11',
      impedance: '6.5%',
      insulation: 'Mineral Oil',
      temperatureClass: 'Class A (105°C)',
      weight: '4200 kg',
      standard: 'IEC 60076',
      biLevel: 'BIL 170 kV (HV), 95 kV (LV)'
    },
    switchgear: {
      manufacturer: 'ABB',
      model: 'ZX2 Vacuum Circuit Breaker',
      serialNumber: `SN-${assetId}`,
      manufactureYear: '2019',
      ratedVoltage: '11 kV',
      ratedCurrent: '630 A',
      breakingCapacity: '25 kA',
      frequency: '50/60 Hz',
      operatingMechanism: 'Spring Charged',
      numberOfPoles: '3',
      insulatingMedium: 'Vacuum',
      controlVoltage: '110 VDC / 220 VAC',
      auxiliarySupply: '110-250 VDC',
      operatingSequence: 'O-0.3s-CO-3min-CO',
      mechanicalLife: '10,000 operations',
      electricalLife: '100 operations at rated capacity',
      standard: 'IEC 62271-100',
      ipRating: 'IP4X'
    },
    motors: {
      manufacturer: 'WEG Electric',
      model: 'W22 Premium Efficiency',
      serialNumber: `SN-${assetId}`,
      manufactureYear: '2020',
      power: '75 kW (100 HP)',
      voltage: '415 V',
      current: '142 A',
      frequency: '50 Hz',
      speed: '1485 RPM',
      phases: '3-Phase',
      efficiency: 'IE3 (95.8%)',
      powerFactor: '0.88',
      insulationClass: 'Class F (155°C)',
      protectionClass: 'IP55',
      mounting: 'B3 (Foot Mounted)',
      duty: 'S1 (Continuous)',
      bearings: 'Deep Groove Ball Bearings',
      ambientTemp: '-15°C to +40°C',
      altitude: 'Up to 1000m',
      standard: 'IEC 60034-1',
      weight: '285 kg'
    },
    generators: {
      manufacturer: 'Cummins Power Generation',
      model: 'C275 D5',
      serialNumber: `SN-${assetId}`,
      manufactureYear: '2019',
      ratedPower: '275 kVA / 220 kW',
      voltage: '400/230 V',
      current: '396 A',
      frequency: '50 Hz',
      phases: '3-Phase, 4-Wire',
      powerFactor: '0.8 Lagging',
      engineModel: 'QSB7-G5',
      engineType: '6 Cylinder, 4-Stroke, Turbocharged',
      fuelType: 'Diesel',
      fuelConsumption: '55 L/hr at 100% Load',
      governorType: 'Electronic Isochronous',
      voltageRegulation: '± 1%',
      alternatorModel: 'Stamford HCI444E',
      coolingSystem: 'Radiator Cooled',
      standard: 'ISO 8528, BS 5000',
      noiseLevel: '76 dB(A) @ 7m',
      dimensions: '2800 x 1100 x 1600 mm',
      weight: '1850 kg'
    },
    cables: {
      manufacturer: 'Prysmian Group',
      model: 'XLPE Armored Power Cable',
      catalogNumber: `CAT-${assetId}`,
      manufactureYear: '2021',
      cableType: '3C x 185 mm²',
      conductor: 'Copper, Stranded',
      insulation: 'XLPE (Cross-Linked Polyethylene)',
      armoring: 'Steel Wire Armored (SWA)',
      outerSheath: 'PVC Black',
      ratedVoltage: 'Uo/U: 0.6/1 kV',
      maxOperatingTemp: '90°C',
      shortCircuitTemp: '250°C (5 seconds)',
      currentCarryingCapacity: '340 A (Buried Direct)',
      dcResistance: '0.106 Ω/km @ 20°C',
      inductance: '0.31 mH/km',
      capacitance: '0.29 µF/km',
      bendingRadius: '12 x Overall Diameter',
      standard: 'IEC 60502-1, BS 6346',
      flameRetardant: 'IEC 60332-3-24',
      cableLength: '150 meters'
    },
    ups: {
      manufacturer: 'Schneider Electric',
      model: 'Galaxy VX 40kVA',
      serialNumber: `SN-${assetId}`,
      manufactureYear: '2020',
      ratedPower: '40 kVA / 40 kW',
      inputVoltage: '380/400/415 VAC ± 20%',
      inputFrequency: '50/60 Hz ± 5 Hz',
      inputPhases: '3-Phase + Neutral',
      outputVoltage: '380/400/415 VAC ± 1%',
      outputFrequency: '50/60 Hz ± 0.01 Hz',
      outputPhases: '3-Phase + Neutral',
      powerFactor: '1.0 (Unity)',
      efficiency: '96% (Online Mode)',
      batteryType: 'VRLA (Valve Regulated Lead Acid)',
      batteryVoltage: '384 VDC',
      backupTime: '10 minutes @ 100% Load',
      transferTime: '0 ms (True Online)',
      overloadCapacity: '125% for 10 min, 150% for 1 min',
      displayType: 'LCD Touchscreen 7"',
      communication: 'Modbus, SNMP, USB',
      standard: 'IEC 62040-1/-2/-3',
      dimensions: '450 x 580 x 1100 mm',
      weight: '180 kg'
    }
  };

  return nameplateSpecs[assetType] || {};
};

export const getAssetPhoto = (assetType) => {
  const photos = {
    transformer: 'https://customer-assets.emergentagent.com/job_grid-inspector/artifacts/kgpqfnfl_power-transformer.jpg',
    switchgear: '/images/switchgear-photo.jpg',
    motors: '/images/motor-photo.jpg',
    generators: '/images/generator-photo.jpg',
    cables: '/images/cable-photo.jpg',
    ups: '/images/ups-photo.jpg'
  };

  return photos[assetType] || 'https://customer-assets.emergentagent.com/job_grid-inspector/artifacts/kgpqfnfl_power-transformer.jpg';
};
